version: '3'

services:

  webserver:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./store:/etc/nginx/www/runs:ro
      - ./scripts/dist/bundle.js:/etc/nginx/scripts/activeTestScript.js
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    profiles: ["production"]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  hardhat:
    build: hardhat
    volumes:
      - ./hardhat/scripts:/scripts:ro
      - ./hardhat/hardhat.config.js:/hardhat.config.js:ro
    ports:
      - "8545:8545"
    profiles: ["dev"]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  keeper:
    build: echo-warmer
    restart: always
    volumes:
      - ./store:/store:rw
      - ./info:/info:rw
    environment:
      - AVENLUUTN_PUB_ADDR
      - AVENLUUTN_PROVIDER=http://hardhat:8545
      - AVENLUUTN_SCRIPT_PROVIDER=http://hardhat:8545
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m

  metadata:
    build: echo-token-metadata
    restart: always
    environment:
      - AVENLUUTN_API_BASE_URI=http://webserver
      - AVENLUUTN_PROVIDER=http:hardhat:8545
      - AVENLUUTN_PUB_ADDR
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
