version: '3'

services:

  webserver:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./store:/etc/nginx/www/runs:ro
      - ./votes:/etc/nginx/www/votes:ro
      - ./scripts/dist/bundle.js:/etc/nginx/scripts/activeTestScript.js
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/certbot --force-renewal --non-interactive --email jesse@jessebmiller.com -d avenluutn-api-dev.squad.games --agree-tos
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  keeper:
    build: echo-warmer
    restart: always
    volumes:
      - ./store:/store:rw
      - ./info:/info:rw
      - ./votes:/votes:rw
    environment:
      - AVENLUUTN_PUB_ADDR
      - AVENLUUTN_PROVIDER
      - AVENLUUTN_SCRIPT_PROVIDER
      - AVENLUUTN_RUN_ALL_NARRATORS
      - AVENLUUTN_TWITTER_BEARER_TOKEN
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  metadata:
    build: echo-token-metadata
    restart: always
    environment:
      - AVENLUUTN_API_BASE_URI=http://webserver
      - AVENLUUTN_PROVIDER
      - AVENLUUTN_PUB_ADDR
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
